### ISSUE TITLE
"java.lang.VerifyError: Bad type on operand stack" while using Enhancement agent

### ISSUE THREAD

**Issue by kobier** [ebean-orm/avaje-ebeanorm-agent#22]
Hi,

recently I started building an application using Play 2.4.3 (for Java) and Ebean ORM. This application is using FakeApplication feature of Play framework extensively for functional testing. To be able to run my functional tests from IntellIJ IDEA (instead of command line tool like activator or sbt), I was about to use Ebean enhancement agent via VM -javaagent parameter.
When I set up VM parameters for my test runner in IntellIJ IDEA 15 as follows:

> -javaagent:C:\avaje-ebeanorm-agent-4.7.1.jar -ea

and try to run my tests, I get following error:

```java
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/client/Client.asDto()Lmodels/client/dto/ClientDto; @16: invokevirtual
  Reason:
    Type 'models/client/dto/ClientDto' (current frame, stack[0]) is not assignable to 'models/client/Client'
  Current Frame:
    bci: @16
    flags: { }
    locals: { 'models/client/Client', 'models/client/dto/ClientDto' }
    stack: { 'models/client/dto/ClientDto', 'java/lang/String' }
  Bytecode:
    0x0000000: bb00 2d59 b700 304c 2b2a b600 34b6 0039
    0x0000010: b600 3c2b 2ab6 0029 b600 1f2b b0       

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:103)
	... 72 more
```

I'm using Java 1.8.0_u60 x64, on Windows 8.1 x64.

I managed to extract this issue to much simpler application, which you can clone from https://github.com/kobier/ebean-test
This repository has two branches: 'master' branch showing a problem and 'fix' branch, that includes simple change to my entity code that resolves the issue.

The problem is apparently caused by this method:

```java
public ClientDto asDto() {
	ClientDto result = new ClientDto();

	result.id = getId().toString();
	result.name = name;

	return result;
}
```

If I move or remove this method from ```Client``` entity, then everything works fine. Renaming this method doesn't help.

To reproduce the problem:

1. Clone mentioned repository
2. Run test class "ClientsTest" in tests folder, using avaje-ebeanorm-agent via -javaagent VM parameter, exception should be thrown
3. Switch to branch 'fix'
4. Run test class again, test passes without any problem

I also tried to fix this problem using version 4.5.3 of "avaje-ebeanorm-agent" (which is the same as version shipped with Play Framework 2.4.3), but I get the same result.

I am able to test & run this example using activator without any problem, problem occurs only if I use  enhancer via -javaagent paramter only.

Any help with this issue will be much appreciated!

Best regards
Maciej

**Comment by rbygrave** [comment]
This example application is a Play application.  In this case Play itself invokes Ebean's enhancement as part of their framework.

As such, I'm not sure that it is valid to additionally have Ebean's enhancement running using the agent. Play does a number of things to the entity beans including changing public field access to intercept.

Have you discussed this issue with the Play people at all?
I presume you have not produced a test case with just Ebean enhancement (and no Play enhancement involved)?

Thanks, Rob.

**Comment by rbygrave** [comment]
Ok, I have created a Ebean only test case.
