### ISSUE TITLE
ENH: Change debug logging from PrintStream to new simple MessageOutput interface

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-agent#25]
On Transformer:

```java

  /**
   * Change the logout to something other than system out.
   */
  public void setLogout(MessageOutput logout) {

```

```java

package com.avaje.ebean.enhance.agent;

/**
 * Debug message output logging by the agent.
 */
public interface MessageOutput {

  /**
   * Log the debug message.
   */
  void println(String message);
}

```

**Comment by kahing** [comment]
How does one actually call this method? I want to be able to redirect the log from System.out to a logger but haven't figured out how to get the instance of the Transformer to call this.

**Comment by rbygrave** [comment]
> how to get the instance of the Transformer

How are you yourself using Transformer? The enhancement code including Transformer are used in many ways by different things (maven plugin, IDEA enhancer plugin, command line standard java agent etc) ... so you need to first state how you are going about using the agent/transformer.

This method is used by the maven plugin, IDEA enhancer plugin and Eclipse IDE plugin for example (which all programmatically use the Transformer).
