### ISSUE TITLE
avaje-ebeanorm-agent 4.9.2 is not publish to maven center repository

### ISSUE THREAD

**Issue by wenzhihong2003** [ebean-orm/avaje-ebeanorm-agent#29]
http://search.maven.org/#search|ga|1|avaje-ebeanorm-agent

the last version is 4.9.1
where is the 4.9.2 version

**Comment by rbygrave** [comment]
It is there:
http://repo1.maven.org/maven2/org/avaje/ebeanorm/avaje-ebeanorm-agent/4.9.2/

... but it is not showing up in search for some reason?

**Comment by rbygrave** [comment]
It went yesterday so this is not normal (that it is not appearing in search.maven.org).

**Comment by rbygrave** [comment]
Hmmm, appears here: http://mvnrepository.com/artifact/org.avaje.ebeanorm/avaje-ebeanorm-agent

**Comment by wenzhihong2003** [comment]
thank you!! 
:+1:
